use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();

    generate_version_file();
}

fn generate_version_file() {
    let cargo_toml_path = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("Cargo.toml");
    let cargo_toml = fs::read_to_string(&cargo_toml_path).expect("Failed to read Cargo.toml");

    let version = extract_version(&cargo_toml).unwrap_or_else(|| "0.0.0".to_string());
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("version.rs");

    let commit = get_git_commit_hash().unwrap_or_else(|| "unknown".to_string());

    let content = format!(
        r#"// Auto-generated by build.rs - DO NOT EDIT
// Version information injected at compile time from Cargo.toml

pub const APP_VERSION: &str = "{version}";
pub const APP_COMMIT: &str = "{commit}";
"#
    );

    fs::write(&dest_path, content).expect("Failed to write version.rs");

    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=../VERSION");
}

fn extract_version(cargo_toml: &str) -> Option<String> {
    for line in cargo_toml.lines() {
        if line.starts_with("version") {
            let parts: Vec<&str> = line.splitn(2, '=').collect();
            if parts.len() == 2 {
                return Some(parts[1].trim().trim_matches('"').to_string());
            }
        }
    }
    None
}

fn get_git_commit_hash() -> Option<String> {
    match std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
    {
        Ok(output) if output.status.success() => {
            String::from_utf8(output.stdout).ok().map(|s| s.trim().to_string())
        }
        _ => None,
    }
}
