"""G-code 后处理器。

将刀具路径转换为特定机床控制器支持的 G-code。
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


class GCodePostProcessor:
    """G-code 后处理器。"""

    def __init__(self, machine_config: dict[str, Any] | None = None) -> None:
        """初始化后处理器。

        Args:
            machine_config: 机床配置参数
        """
        self._machine_config = machine_config or {}
        self._gcode_lines: list[str] = []

    def set_machine_config(self, config: dict[str, Any]) -> None:
        """设置机床配置。

        Args:
            config: 机床配置参数
        """
        self._machine_config = config
        logger.info("Machine configuration updated")

    def generate_header(self) -> str:
        """生成 G-code 头部。

        Returns:
            G-code 头部字符串
        """
        lines = [
            "%",
            "O0001 (Generated by CAM system)",
            "(Units: MM)",
            "(Toolpath: Operation 1)",
        ]

        # Add machine-specific header
        if self._machine_config.get("controller") == "fanuc":
            lines.append("G90 G94 G17 G21")  # Absolute, feed/min, XY plane, metric
        elif self._machine_config.get("controller") == "siemens":
            lines.append("G90 G94 G71")  # Absolute, feed/min, metric

        return "\n".join(lines)

    def generate_footer(self) -> str:
        """生成 G-code 尾部。

        Returns:
            G-code 尾部字符串
        """
        lines = [
            "M5 (Spindle stop)",
            "M9 (Coolant off)",
            "G91 G28 Z0 (Return Z to home)",
            "G28 X0 Y0 (Return XY to home)",
            "M30 (Program end)",
            "%",
        ]
        return "\n".join(lines)

    def convert_toolpath(
        self,
        toolpath: Any,
        include_rapid: bool = True,
    ) -> str:
        """将刀具路径转换为 G-code。

        Args:
            toolpath: 刀具路径数据
            include_rapid: 是否包含快速移动

        Returns:
            G-code 字符串
        """
        self._gcode_lines = []

        # Generate header
        self._gcode_lines.append(self.generate_header())

        # 刀具路径转换（待实现）
        # - 将直线移动转换为 G1
        # - 将圆弧移动转换为 G2/G3
        # - 将快速移动转换为 G0
        # - 添加主轴和冷却液命令

        # Generate footer
        self._gcode_lines.append(self.generate_footer())

        return "\n".join(self._gcode_lines)

    def save_to_file(self, gcode: str, output_path: str) -> bool:
        """保存 G-code 到文件。

        Args:
            gcode: G-code 字符串
            output_path: 输出文件路径

        Returns:
            保存是否成功
        """
        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(gcode)
            logger.info("G-code saved to: %s", output_path)
            return True
        except Exception as e:
            logger.error("Failed to save G-code: %s", e, exc_info=True)
            return False
