"""initial_schema

Revision ID: be7e8d82d196
Revises: 
Create Date: 2026-05-19 23:06:13.803530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7e8d82d196'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Permission display name'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='Permission code identifier'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Permission description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Role display name'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='Role code identifier'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Role description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)

    op.create_table('training_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False, comment='Task type identifier (lnn_training, lnn_inference, etc.)'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Task status: pending/running/completed/failed/cancelled'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Progress percentage (0-100)'),
    sa.Column('params', sa.JSON(), nullable=True, comment='Task parameters as JSON'),
    sa.Column('result', sa.JSON(), nullable=True, comment='Task result data as JSON'),
    sa.Column('error', sa.String(length=2048), nullable=True, comment='Error message if task failed'),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Task creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Last update timestamp'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_training_tasks_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_training_tasks_owner', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index('idx_training_tasks_status_type', ['status', 'task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_tasks_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_training_tasks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_role_permissions_permission', ['permission_id'], unique=False)
        batch_op.create_index('idx_role_permissions_role', ['role_id'], unique=False)

    # Create rule_groups and rules tables (for fresh database rebuild)
    # These tables already existed in the previous codebase; IF NOT EXISTS ensures idempotency
    op.execute("""
        CREATE TABLE IF NOT EXISTS rule_groups (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL UNIQUE,
            description TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS rules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            group_id INTEGER,
            conditions_json TEXT NOT NULL,
            logic_operator TEXT NOT NULL DEFAULT 'AND',
            result_json TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            priority INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (group_id) REFERENCES rule_groups(id) ON DELETE SET NULL
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_rules_group_id ON rules(group_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_rules_status ON rules(status)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_rules_name ON rules(name)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_role_permissions_role')
        batch_op.drop_index('idx_role_permissions_permission')

    op.drop_table('role_permissions')
    with op.batch_alter_table('training_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_training_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_training_tasks_owner_id'))
        batch_op.drop_index(batch_op.f('ix_training_tasks_idempotency_key'))
        batch_op.drop_index('idx_training_tasks_status_type')
        batch_op.drop_index('idx_training_tasks_owner')
        batch_op.drop_index('idx_training_tasks_created_at')

    op.drop_table('training_tasks')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_code'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')

    # Drop rule_groups and rules tables (for downgrade)
    op.execute("DROP TABLE IF EXISTS rules")
    op.execute("DROP TABLE IF EXISTS rule_groups")

    # ### end Alembic commands ###
